# Site settings
title: Amit M Mangalvedkar
twitter_username: amitmangalvedka
name: Amit M Mangalvedkar

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: GitHub
   url: https://github.com/amitmangalvedkar
 - title: LinkedIn
   url: https://www.linkedin.com/in/amit-mangalvedkar/

#Any buzzword skills you want to include
skills:
 - Java
 - Watson IoT Platform
 - TRIRIGA Building Insights
 - Docker
 - API design
 - ReST


#Work experience is required
roles:
 - title: Senior Engineer
   start: 2015
   end: Ongoing
   employer: IBM India

#Education is required
education:
 - level: Master of Technology (M.Tech.)
   date: 2001
   school: IIT Bombay

#List of interesting Github repo/projects to include - optional
github:
 - amitmangalvedkar/amitmangalvedkar.github.io

